name: Deploy Function App

on:
  push:
    branches:
      - main  # Deploys when you push changes to the main branch
  workflow_dispatch: # Allows manual deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function App
        uses: azure/functions-action@v1
        with:
          app-name: adf-file-trigger
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
